before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell hunspell-ru hunspell-en-us
  - curl -s http://extensions.libreoffice.org/extension-center/russian-spellcheck-dictionary.-based-on-works-of-aot-group | grep -oP "http://extensions.libreoffice.org/extension-center/russian-spellcheck-dictionary.-based-on-works-of-aot-group/pscre[^\"]+" | sort -r | head -1 | wget -q -i - -O dictionary.otx
  - unzip dictionary.otx
script:
  - git diff HEAD^ | hunspell -d russian-aot,en_US | grep "^&"

notifications:
  email: false
