language: go
sudo: required

dist: trusty
group: deprecated-2017Q4

git:
  depth: 3
  submodules: false

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - sudo env PATH=$PATH GOPATH=$GOPATH sh files/check-install.sh

script:
  - sh files/check.sh
  - sh files/run_on_master.sh

notifications:
  email: false
