before_install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell hunspell-ru hunspell-en-us hunspell-de-de
  - curl -s https://extensions.libreoffice.org/extensions/russian-spellcheck-dictionary.-based-on-works-of-aot-group > .dict_page
  - cat .dict_page | grep -oP "<a href.+title=\"Current release for the project\"" | grep -oP "https://extensions.libreoffice.org/extensions/russian-spellcheck-dictionary.-based-on-works-of-aot-group/[^\"]+" > .current_release
  - echo -n $(cat .current_release) > .current_release
  - echo -n "/@@download[^\"]+" >> .current_release
  - cat .dict_page | grep -oP -f .current_release | wget -q -i - -O dictionary.otx
  - unzip dictionary.otx
  - git config core.quotepath false
  - go get -u github.com/peterhellberg/serve
  - go get -u github.com/russross/blackfriday-tool
  - find *.md -exec blackfriday-tool {} {}.html \;
  - nohup serve -addr="0.0.0.0:80" >/dev/null 2>&1 &
  - git diff HEAD^ --name-status | grep "^D" -v | sed 's/^.\t//g' > changed_files_links
  - sed -i -e 's/^/http:\/\/localhost\//' changed_files_links
  - sed -i -e 's/$/.html/' changed_files_links

script:
  - wget --spider -erobots=off -r -nd -H -l 1 -i changed_files_links
  - cat broken_links.log
  - sh files/.travis.sh

notifications:
  email: false
