before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell hunspell-ru hunspell-en-us hunspell-de-de
  - curl -s https://extensions.libreoffice.org/extensions/russian-spellcheck-dictionary.-based-on-works-of-aot-group | grep -oP "<a href.+title=\"Current release for the project\"" | grep -oP "https://extensions.libreoffice.org/extensions/russian-spellcheck-dictionary.-based-on-works-of-aot-group/[^\"]+" | wget -q -i - -O dictionary.otx
  - unzip dictionary.otx
  - git config core.quotepath false
script:
  - sh files/.travis.sh

notifications:
  email: false
